name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: git config
        run: |
          git config --global --add safe.directory /github/workspace

  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Subversion
        run: sudo apt-get install -y subversion

      - name: WordPress Plugin Deploy
        uses: idehweb/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{secrets.SVN_PASSWORD}}
          SVN_USERNAME: ${{secrets.SVN_USERNAME}}
          SLUG: login-with-phone-number